name: Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Debug Project Structure
        run: find . -name "*.csproj"

      - name: Restore Dependencies
        run: dotnet restore **/*.csproj  # Automatically finds the correct .csproj file

      - name: Build Application
        run: dotnet build **/*.csproj --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish **/*.csproj --configuration Release --output ./publish --no-build

      - name: Debug Published Files
        run: ls -R ./publish

      - name: Zip Published Files
        run: zip -r release.zip ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'decordova-web-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
