name: Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Debug: List Files
        run: ls -R  # Check file structure for debugging

      - name: Restore Dependencies
        run: dotnet restore DotNetCoreSqlDb.csproj
        working-directory: msdocs-app-service-sqldb-dotnetcore

      - name: Build Application
        run: dotnet build DotNetCoreSqlDb.csproj --configuration Release --no-restore
        working-directory: msdocs-app-service-sqldb-dotnetcore

      - name: Publish Application
        run: dotnet publish DotNetCoreSqlDb.csproj --configuration Release --output ./publish --no-build
        working-directory: msdocs-app-service-sqldb-dotnetcore

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'decordova-web-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: msdocs-app-service-sqldb-dotnetcore/publish
